FROM python:3.9.18-slim

LABEL authors="tebarius"
LABEL version="1.0"
LABEL description="Simple QR-Code-Generator-Server"

WORKDIR /app

COPY ./templates ./Flask-QR.py ./requirements.txt /app/

RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 80

CMD ["python", "Flask-QR.py"]