FROM python:slim

LABEL authors="tebarius"
LABEL version="1.0"
LABEL description="Simple QR-Code-Generator-Server"

WORKDIR /app
COPY ./app /app/

RUN apt-get update && apt-get install -y gcc zlib1g-dev libjpeg-dev
#RUN python -m pip install --upgrade pip
#RUN python -m pip install --upgrade pillow
RUN pip install --trusted-host pypi.python.org -r requirements.txt

EXPOSE 80

CMD ["python", "Flask-QR.py"]