name: trivy-show-all
run-name: Trivy - Show All Image:${{ github.event.inputs.image_tag || 'latest' }}

on:
  workflow_dispatch: # Manuelles Auslösen des Workflows
    inputs:
      image_tag:
        description: 'Tag für das zu scannende Docker-Image z.B. latest'
        required: true
        default: 'latest'

env:
  image_name: flask-qr
  image_tag: ${{ github.event.inputs.image_tag || 'latest' }}
  registry_gitea: gitea.tebarius.duckdns.org
  user: tebarius

jobs:
  trivy_image_scan:
    runs-on: ubuntu-latest
    container: aquasec/trivy:latest
    strategy:
      matrix:
          platform: [linux/amd64, linux/arm64]
    steps:
      - name: Scan Image with trivy
        run: |
          trivy image \
          --username ${{ env.user }} \
          --password ${{ secrets.CI_TOKEN_PULL_GITEA_REGISTRY }} \
          --scanners vuln,misconfig,secret \
          --platform ${{ matrix.platform }} \
          ${{ env.registry_gitea }}/${{ env.user }}/${{ env.image_name }}:${{ env.image_tag }}
